version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_HOST: '%'

  app:
    image: bitexchange:1.0
    depends_on:
      - db
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/bitexchange
      - gems:/gems
    links:
      - db

volumes:
  db:
  gems:
