version: "3"

services:
  mysql:
    image: "mysql:5.7"
    volumes:
      - mysql:/var/lib/mysql/data

  app:
    depends_on:
      - "mysql"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/bitexchange
      - gems:/gems
 
volumes:
  mysql:
  gems:
