default: &default
  adapter:  mysql2
  encoding: utf8
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host:     db
  username: root
  password: ''

development:
  <<: *default
  database: bitexchange_development

test:
  <<: *default
  database: bitexchange_test

production:
  <<: *default
  database: bitexchange_development
